#!/bin/bash

setfont ter-132b

verify_system() {
    if [[ ! -f /usr/bin/pacstrap ]]; then
        echo "Not in arch live env"
        exit 1
    fi

    if [[ "$(id -u)" != "0" ]]; then
        echo "Not running as root"
        exit 1
    fi

    if [[ "$(cat /sys/firmware/efi/fw_platform_size)" != "64" ]]; then
        echo "Not booted in a supported mode (x64 UEFI)"
        exit 1
    fi

    if ! ping -qn -c 1 ping.archlinux.org &>/dev/null; then
        echo "No internet connection"
        exit 1
    fi

    if [[ "$(timedatectl show -p NTPSynchronized --value)" != "yes" ]]; then
        echo "System clock is not synchronized"
        exit 1
    fi
}

get_user_input() {
    local _username
    local _password _password_confirm
    local _compname # damn linux for making 'hostname' a command
    local _timezone
    local _disk _partition_suffix

    while true; do
        read -p "Username: " _username
        if [[ -z "${_username}" ]]; then
            echo "Cannot be blank"
            continue
        fi

        if [[ ! "${_username}" =~ ^[a-zA-Z0-9]+$ ]]; then
            echo "No special chars"
            continue
        fi
        break
    done

    while true; do
        read -p "Password: " _password
        if [[ -z "${_password}" ]]; then
            echo "Cannot be blank"
            continue
        fi

        read -p "Confirm: " _password_confirm
        if [[ "${_password}" != "${_password_confirm}" ]]; then
            echo "Passwords did not match"
            continue
        fi
        break
    done

    while true; do
        read -p "Computer Name: " _compname
        if [[ -z "${_compname}" ]]; then
            echo "Cannot be blank"
            continue
        fi

        if [[ ! "${_compname}" =~ ^[a-zA-Z0-9]+$ ]]; then
            echo "No special chars"
            continue
        fi
        break
    done

    _timezone="$(curl -s -f -m 5 https://ipapi.co/timezone)"
    while true; do
        read -r -p "Detected timezone: '${_timezone}'. Is this correct? (Y/n): "
        case "${REPLY:-Y}" in
            [Yy]* ) _timezone="${_timezone}" ;;
            [Nn]* ) _timezone="$(tzselect)" ;;
        esac

        if [[ -f "/usr/share/zoneinfo/${_timezone}" ]]; then
            break
        else
            echo "Timezone: '${_timezone:-${REPLY}}' is incorrect"
            continue
        fi
    done

    select _disk in $(lsblk -npdo name); do
        if [[ -z "${_disk}" ]]; then
            echo "Must select a drive"
            continue
        fi

        if [[ ! -b "${_disk}" ]]; then
            echo "Drive '${_disk}' is not valid"
            exit 1
        fi

        if [[ "${_disk}" =~ "nvme" ]]; then
            _partition_suffix="p"
        else
            _partition_suffix=""
        fi

        read -p "Destroy data on '${_disk}'? (y/N): "
        if [[ "${REPLY:-N}" =~ [yY] ]]; then
            break
        else
            echo "Aborted by user"
            exit 0
        fi
    done

    export username="${_username}"
    export password="${_password}"
    export compname="${_compname}"
    export timezone="${_timezone}"
    export disk="${_disk}"
    export boot_partition="${_disk}${_partition_suffix}1"
    export root_partition="${_disk}${_partition_suffix}2"
}

prepare_disk() {
    if mountpoint -q /mnt; then
        umount -R /mnt
    fi
    
    sgdisk -Z "${disk}"
    sgdisk -a 2048 -o "${disk}"
    sgdisk -n 1::+1GiB --typecode=1:ef00 --change-name=1:'EFIBOOT' "${disk}"
    sgdisk -n 2::-0 --typecode=2:8300 --change-name=2:'ROOT' "${disk}"
    partprobe "${disk}"
    mkfs.fat -F 32 "${boot_partition}"
    mkfs.ext4 "${root_partition}"
    mount "${root_partition}" /mnt
    mount --mkdir "${boot_partition}" /mnt/boot
}

install_arch() {
    pacman -Sy --noconfirm archlinux-keyring
    pacman -S --noconfirm --needed reflector
    
    reflector_args=(
        --completion-percent 100
        --country "United States"
        --latest 6
        --protocol https
        --verbose
        --sort rate
        --save /etc/pacman.d/mirrorlist
    )
    
    reflector "${reflector_args[@]}"
    
    sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
    
    pacstrap_pkgs=(
        amd-ucode
        base
        base-devel
        bash-completion
        efibootmgr
        grub
        less
        linux
        linux-firmware
        man-db
        man-pages
        nano
        networkmanager
        sudo
        zram-generator
        zstd
    )
    
    pacstrap -K /mnt "${pacstrap_pkgs[@]}"
}

configure_arch() {
    cp -r ./archsetup /mnt/etc/skel/archsetup
	
    genfstab -U /mnt >> /mnt/etc/fstab
	
    arch-chroot /mnt /bin/bash -s <<- EOF
        # time
		ln -sf /usr/share/zoneinfo/"${timezone}" /etc/localtime
		hwclock --systohc

		# localization
		sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
		locale-gen
		echo "LANG=en_US.UTF-8" > /etc/locale.conf

		# network config
		echo "${compname}" > /etc/hostname
		systemctl enable NetworkManager.service

		# install bootloader
		grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
		sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& quiet /' /etc/default/grub
		grub-mkconfig -o /boot/grub/grub.cfg
		efibootmgr -c -d "${disk}" -p 1 -L "Arch Linux" -l /EFI/GRUB/grubx64.efi

		# setup user account
		useradd -m -G wheel -s /bin/bash "${username}"
		echo "${username}:${password}" | chpasswd
		sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
		sed -i 's/^#Color/Color\nILoveCandy/' /etc/pacman.conf
		sed -i '/#\[multilib\]/,/#Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf
		sed -i 's/^# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers
		sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers
        rm -rf /etc/skel/archsetup

        # zram config file
        cat <<- Z_EOF > /etc/systemd/zram-generator.conf
            [zram0]
            zram-size = min(ram / 2, 4096)
            compression-algorithm = zstd
        Z_EOF

		exit
	EOF
}

verify_system
get_user_input
prepare_disk
install_arch
configure_arch

read -p "Installation complete. Reboot now? [y/N]: "
if [[ "${REPLY:-NO}" =~ ^[Yy] ]]; then
    systemctl reboot
fi