#!/bin/bash

install_yay() {
    if ! git clone https://aur.archlinux.org/yay /tmp/yay; then
        echo "Failed to clone 'yay' repository"
        return 1
    elif ! (cd /tmp/yay && makepkg -si --noconfirm); then
        echo "Failed 'makepkg' for 'yay'"
        return 1
    else
        return 0
    fi
}

install_yay_pkgs() {
    if [[ -f yay.pkgs ]]; then
        yay -S --noconfirm --needed - < yay.pkgs
    else
        echo "No 'yay.pkgs' file found. Skipping 'yay' package installation."
    fi
fi

sudo pacman -Sy

if [[ -f pacman.pkgs ]]; then
    sudo pacman -S --noconfirm --needed - < pacman.pkgs
else
    echo "No 'pacman.pkgs' file found. Skipping 'pacman' package installation."
fi  

if command -v yay 1>/dev/null; then
    echo "Already installed: 'yay'"
    install_yay_pkgs
else
    if ! install_yay; then
        echo "Failed to install: 'yay'"
    else
        install_yay_pkgs
    fi
fi